---
  extends: airbnb-base
  env:
    node: true
    mocha: true
    es6: true
  parser: "@typescript-eslint/parser"
  parserOptions:
    sourceType: module
  plugins:
    - import
    - promise
  rules:
    generator-star-spacing:
      - 2
      - before: true
        after: true
    no-shadow: 0
    import/no-unresolved: 0
    import/extensions: 0
    import/prefer-default-export: 1
    require-yield: 0
    no-param-reassign: 0
    comma-dangle: 0
    no-underscore-dangle: 0
    no-control-regex: 0
    import/no-extraneous-dependencies:
      - 2
      - devDependencies: true
    func-names: 0
    no-unused-expressions: 0
    prefer-arrow-callback: 1
    no-use-before-define:
      - 2
      - functions: false
    space-before-function-paren:
      - 2
      - always
    max-len:
      - 2
      - 120
      - 2
    semi:
      - 2
      - never
    strict:
      - 2
      - global
    arrow-parens: 0
    arrow-body-style: 0
    class-methods-use-this: 0
    consistent-return: 1
    no-useless-constructor: 0
    no-unused-vars: 1
    no-console: 0
    padded-blocks: 0
    prefer-template: 1
    no-undef: 1 # https://github.com/typescript-eslint/typescript-eslint/issues/342
